[package]
name = "linewise"
version = "0.1.0"
edition = "2021"

[dependencies]
convolve2d = { version = "0.2.0", features = [ "image" ] }
either = "1.13.0"
image = "0.25.2"
nalgebra = "0.33.0"
rand = { version = "0.8.5", features =  [ "small_rng" ] }
svg = "0.18.0"


[profile.release]
debug = true
