[project]
name = "hello"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["drawsvg>=2.4.0", "termcolor>=3.1.0", "watchdog>=6.0.0"]

[project.optional-dependencies]
dev = ["ruff>=0.1", "isort>=6.0"]
